apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-assignment-2
  namespace: default-1713085409400
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctse-assignment-2
  template:
    metadata:
      labels:
        app: ctse-assignment-2
    spec:
      containers:
      - name: ctse-assignment-2
        image: nsfwregistry.azurecr.io/ctse/ctse-assignment-2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: MONGODB_URI
          value: "<key>"
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
