name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
                
    - name: 'Build the Docker image'
      uses: docker/login-action@v3
      with:
        registry: nsfwregistry.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker build . --file Dockerfile --tag nsfwregistry.azurecr.io/ctse/ctse-assignment-2:latest
        docker push nsfwregistry.azurecr.io/ctse/ctse-assignment-2:latest
    
    - name: Configure Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        mkdir $HOME/.kube/
        echo "$KUBECONFIG" | base64 --decode > $HOME/.kube/config

    - name: Update Deployment
      run: |
        kubectl set image deployment/ctse-assignment-2 ctse-assignment-2=nsfwregistry.azurecr.io/ctse/ctse-assignment-2:latest --namespace default-1713085409400
