name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
                
    - name: 'Build the Docker image'
      uses: docker/login-action@v3
      with:
        registry: nsfwregistry.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker build . --file Dockerfile --tag nsfwregistry.azurecr.io/ctse/ctse-assignment-2:latest
        docker push nsfwregistry.azurecr.io/ctse/ctse-assignment-2:latest
    
